services:
  - type: web
    name: agrotrust-backend
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker fastapi_app.main:app
    envVars:
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: agrotrust-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10.0

databases:
  - name: agrotrust-db
    plan: free
